#!/bin/bash
for f in src/ext/*.java
do
	filename=`basename $f .java`
	echo "Compiling $filename.java..."
	javac -cp src src/ext/$filename.java -encoding utf8 -d bin/lib
done
cd bin/lib
for f in ext/*.class
do
	filename=`basename $f .class`
	echo "Creating $filename.jar..."
	jar cvfe $filename.jar ext.$filename ./ext
done
rm -rf ext
rm -rf main
echo "Done."